/**
 * backend/lib/confirm-email.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Builds the branded email confirmation email sent via donotreply.dobium@gmail.com.
 * The confirmation link is generated by Supabase admin (generateLink) and
 * embedded here — we own the sending, not Supabase.
 * ─────────────────────────────────────────────────────────────────────────────
 */

const PLATFORM_URL = process.env.PLATFORM_URL || 'https://dobium.com';

function escHtml(str) {
  return String(str || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

/**
 * Build the HTML confirmation email.
 *
 * @param {Object} opts
 * @param {string} opts.name           - display name (may be null)
 * @param {string} opts.confirmUrl     - the Supabase-generated confirmation link
 */
function buildConfirmHtml({ name, confirmUrl }) {
  const year = new Date().getFullYear();
  const greeting = name ? `Hey ${escHtml(name)},` : 'Hey there,';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
  <title>Confirm your Dobium account</title>
</head>
<body style="margin:0;padding:0;background-color:#0a0f1e;font-family:Arial,Helvetica,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#0a0f1e;padding:32px 16px 48px;">
    <tr><td align="center">

      <table width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;border-radius:16px;overflow:hidden;border:1px solid rgba(212,175,55,0.2);box-shadow:0 0 48px rgba(212,175,55,0.06);">

        <!-- Gold top bar -->
        <tr><td style="height:4px;background:linear-gradient(90deg,#7a5c10,#b8952a,#d4af37,#f0cc6a,#d4af37,#b8952a,#7a5c10);font-size:0;line-height:0;">&nbsp;</td></tr>

        <!-- Logo -->
        <tr><td align="center" style="padding:24px 32px 20px;background-color:#071428;">
          <img src="${PLATFORM_URL}/Logo-Title.png" alt="Dobium" width="130" style="display:block;height:auto;border:0;margin:0 auto;" />
        </td></tr>

        <!-- Hero -->
        <tr><td align="center" style="padding:36px 32px 28px;background:linear-gradient(160deg,#0c1e40 0%,#071428 60%,#04101f 100%);">
          <div style="width:56px;height:56px;border-radius:14px;background:rgba(212,175,55,0.12);border:1.5px solid rgba(212,175,55,0.5);margin:0 auto 18px;text-align:center;line-height:56px;font-size:26px;">✉️</div>
          <h1 style="margin:0 0 10px;font-size:24px;font-weight:900;color:#f1f5f9;line-height:1.2;">Confirm your email</h1>
          <p style="margin:0;font-size:14px;color:#64748b;line-height:1.6;">One click and you're in.</p>
        </td></tr>

        <!-- Greeting -->
        <tr><td style="background:#0a1628;padding:24px 32px;border-top:1px solid rgba(212,175,55,0.1);border-bottom:1px solid rgba(212,175,55,0.1);">
          <p style="margin:0 0 10px;font-size:16px;font-weight:700;color:#f1f5f9;">${greeting}</p>
          <p style="margin:0;font-size:13px;color:#94a3b8;line-height:1.8;">
            Thanks for signing up for <strong style="color:#d4af37;">Dobium Prediction Markets</strong>.
            Click the button below to confirm your email address and activate your account.
            Your <strong style="color:#d4af37;">$10,000 paper trading credit</strong> is waiting.
          </p>
        </td></tr>

        <!-- CTA -->
        <tr><td align="center" style="background:#071428;padding:36px 32px;">
          <a href="${escHtml(confirmUrl)}"
             style="display:inline-block;padding:15px 52px;background:linear-gradient(135deg,#b8952a 0%,#d4af37 50%,#e8c645 100%);color:#0a0f1e;font-size:15px;font-weight:900;text-decoration:none;border-radius:10px;letter-spacing:0.3px;box-shadow:0 4px 20px rgba(212,175,55,0.3);">
            Confirm my account →
          </a>
          <p style="margin:20px 0 0;font-size:11px;color:#334155;line-height:1.6;">
            Button not working? Copy and paste this link into your browser:<br/>
            <a href="${escHtml(confirmUrl)}" style="color:#64748b;word-break:break-all;">${escHtml(confirmUrl)}</a>
          </p>
        </td></tr>

        <!-- Expiry note -->
        <tr><td style="background:#04101f;padding:16px 32px;border-top:1px solid rgba(255,255,255,0.04);">
          <p style="margin:0;font-size:12px;color:#334155;text-align:center;line-height:1.6;">
            This link expires in <strong style="color:#475569;">24 hours</strong>.
            If you didn't create a Dobium account, you can safely ignore this email.
          </p>
        </td></tr>

        <!-- Footer -->
        <tr><td align="center" style="padding:18px 32px 22px;background:#04101f;">
          <p style="margin:0 0 4px;font-size:11px;color:#334155;">© ${year} Dobium · All rights reserved.</p>
          <p style="margin:0;font-size:10px;color:#1e293b;line-height:1.6;">dobium.com</p>
        </td></tr>

        <!-- Gold bottom bar -->
        <tr><td style="height:3px;background:linear-gradient(90deg,#7a5c10,#b8952a,#d4af37,#f0cc6a,#d4af37,#b8952a,#7a5c10);font-size:0;line-height:0;">&nbsp;</td></tr>

      </table>

    </td></tr>
  </table>
</body>
</html>`;
}

module.exports = { buildConfirmHtml };
